name: Update Calendars

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main

jobs:
  update-calendars:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-js-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Generate calendars
      env:
        GITHUB_REPOSITORY: 'stirlo/zmanim_ICS'
      run: node ics-generator.js

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendars $(date +'%Y-%m-%d %H:%M:%S')" && git push)
